/// Chord progressions that are known to be syntactically valid. Mirrors the
/// worked examples in `lib/model/Tokenizer.txt` and the commented-out
/// `testCases` list in `lib/model/token.dart`. Used by the parser and
/// validator tests.
const List<String> validProgressions = [
  'I-vi-IV-V',
  'I-(I-III-I-VII)-VI-V I-(I-III-I-VII)-VI-(VII-VI)-V',
  'i-III-iv :2 i-III-iv-V',
  'III-VIM7 III-(VIM7-V7)',
  'i-VII-VI-♯VII III',
  'I-I+-I6-I7-IV-iv6-I-V9',
  'VI7-i :2 II7-V7',
  'i-III-viø7-IV',
  'i i-iv-VII i VI-III',
  'i-VI-IV7-VI-VII-I-VI-IV7-Vsus4-V',
  'v-(v-♯iv)-iv',
  'I-iii-I-iii-vi-(V)-IV-V-vi-V',
  'i-VI-VII(add9)-♯vi-III-♭I',
  'I-♯iv7-IVM7-(ii7-V11)',
  'i7-ii7-III6-IV i7/5-IV/3-i7/5-IV/5',
  'I-v(add11)-v(add11)-ii7',
  'IV7sus2-I-V6 :2 IV-IVM7 :1 ',
  'i-VII-IV/3-V :1 i-VII-VI-V i',
  'i-i/5-iv i-V-i',
  'i K+M2 i',
  'I5-VII5-I5 VI5-V5 ♯VII5-V5 :3 i-♭II',
  'i-VII-VI-ivsus2-V7-V7/3',
  'I5-♭II5-I5',
  'V7♭9',
  'I-I I5-VIno5-♭VIIno5-vii I-V',
  'i-v7 :1 K–M2 III-VII i-VI IV-V (V-VII)',
  'I6-♭III6-♭VII-vi-♭VI-Vsus4-(I6-♭vii°)-♭II',
  'I-vi-IV-V :2 IV-V/3-vi-II I-V/3-vi-II',
  'I-(V/5-I)-IV-V',
  'I(add9)-III-vi-ii-V',
  'VI-V-i ii/VI-V/VI-VI-V-i',
  'ii-V-ii-V I-IV7-iii-♯ii° ii-V-ii-V-I',
  'i-IIIM7♯5-III-IV-VIM7-(VII)-i :1 III-IV-VIM7-i-(VII)-III-VII-IV',
  'VI-III-V7-(i-VII/3-III-IV-V) VI-III-iv7-V7',
  'i/3-Vsus4/5-v/5',
];
